---
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - homeassistant_config:/config
      - /run/dbus:/run/dbus:ro # for bluetooth
    ports:
      - 8123:8123
    devices:
      - /dev/ttyACM0:/dev/ttyACM0 # sonoff zigbee dongle
    restart: unless-stopped

volumes:
  homeassistant_config:
    driver: local
