services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /home/hercules/apps/jellyfin/config:/config
      - /home/hercules/apps/jellyfin/cache:/cache
      - type: bind
        source: /home/hercules/media/movies
        target: /media/movies
      - type: bind
        source: /home/hercules/media/shows
        target: /media/shows
    ports:
      - 8096:8096
    restart: 'unless-stopped'
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - /home/hercules/apps/jellyfin/config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
